### ISSUE TITLE
Definir coisas para novos membros

### ISSUE THREAD

**Issue by yaansz** [Softawii/capivara#33]
Talvez uma mensagem (embed)
Cargos e etc...

**Comment by yaansz** [comment]
Módulo de Auth substitui isso? @FerroEduardo @Pedroo-H

**Comment by FerroEduardo** [comment]
Isso seria um módulo de Welcome

**Comment by Pedroo-H** [comment]
Depende da forma que for feito. Podemos criar mais de um tipo de auth. Pode
ser por e-mail ou aceitar termos de um canal principal.

Caso seja um auth com mais opções, como acima, acho que substitui sim.

Em dom., 24 de jul. de 2022 16:26, Yan Figueiredo ***@***.***>
escreveu:
